# Generated by Django 6.0.5 on 2026-06-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='age',
            field=models.IntegerField(),
        ),
    ]
